In [1]:
import pandas as pd
import numpy as np

In [2]:
# 시도 지명 바꾸기
def city_sido_change(sido):
    if sido =='서울':
        sido = '서울특별시'
    elif sido =='인천':
        sido = '인천광역시'
    elif sido =='경기':
        sido ='경기도'
        
    return sido

In [3]:
# 오류 행정동 코드 바꾸기
def SGGcode_change(SGG_CD):
    if(SGG_CD=='23030'):
        SGG_CD='23090'
    else:
        SGG_CD
    
    return SGG_CD

In [6]:
# EQ5D, 소득, 교육 PCA => 사회불평등 지수(독립변인)
socio_index = pd.read_excel('../data/temporary_storage/1_soc_index.xlsx')
socio_index = socio_index.astype({'행정구역코드':str})

socio_index['시도'] = socio_index['시도'].apply(lambda x:city_sido_change(x))
socio_index['행정구역코드'] = socio_index['행정구역코드'].apply(lambda x:SGGcode_change(x))

socio_index

        시도  시군구    년도 행정구역코드  사회적_불평등_지수
0    서울특별시  종로구  2015  11010    1.602852
1    서울특별시  종로구  2016  11010    1.630460
2    서울특별시  종로구  2017  11010    1.706963
3    서울특별시  종로구  2018  11010    1.322523
4    서울특별시   중구  2015  11020   -0.162058
..     ...  ...   ...    ...         ...
259    경기도  가평군  2018  31370   -1.314690
260    경기도  양평군  2015  31380   -2.159563
261    경기도  양평군  2016  31380   -1.164249
262    경기도  양평군  2017  31380   -0.595251
263    경기도  양평군  2018  31380   -1.799638

[264 rows x 5 columns]

In [8]:
# 통제 변인
cntr_val = pd.read_csv('../data/temporary_storage/2_concat_control_variable.csv')
cntr_val

,시도,시군구,행정구역코드,법정구역코드,년도,EQ5D,학사_비율,소득액,실업급여지급자수(년),실업급여지급건수(년),...,도로_노드_개수,도로_링크_개수,버스_노선_개수,버스_정류장_개수,대중교통_노선_개수,대중교통_정류장_역_개수,대중교통_노선_면적,대중교통_역_노선_면적,도로_노드_면적,도로_링크_면적
0,서울,종로구,11010,11110,2015,0.950,0.388313,2755607,3443,13435,...,346,979,144,396,149.0,410.0,6.230948e-06,0.000017,0.000014,0.000041
1,서울,종로구,11010,11110,2016,0.968,0.388313,2737610,3304,12419,...,346,979,144,396,149.0,410.0,6.230951e-06,0.000017,0.000014,0.000041
2,서울,종로구,11010,11110,2017,0.957,0.388313,2870292,3214,12277,...,346,979,144,396,149.0,410.0,6.230976e-06,0.000017,0.000014,0.000041
3,서울,종로구,11010,11110,2018,0.952,0.388313,3007628,3265,12960,...,346,979,144,396,149.0,410.0,6.230838e-06,0.000017,0.000014,0.000041
4,서울,중구,11020,11140,2015,0.952,0.327387,2922120,3034,11835,...,272,731,170,241,176.0,264.0,1.766971e-05,0.000027,0.000027,0.000073
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
259,경기,가평군,31370,41820,2018,0.970,0.185385,1893631,1270,4938,...,932,2254,71,919,72.0,923.0,8.538180e-08,0.000001,0.000001,0.000003
260,경기,양평군,31380,41830,2015,0.952,0.232083,1571897,1671,6827,...,1113,2584,178,1096,179.0,1105.0,2.039442e-07,0.000001,0.000001,0.000003
261,경기,양평군,31380,41830,2016,0.950,0.232083,1637534,1720,6935,...,1113,2584,178,1096,179.0,1105.0,2.039441e-07,0.000001,0.000001,0.000003
262,경기,양평군,31380,41830,2017,0.953,0.232083,1708265,1833,7505,...,1113,2584,178,1096,179.0,1105.0,2.039437e-07,0.000001,0.000001,0.000003
263,경기,양평군,31380,41830,2018,0.947,0.232083,1785488,2013,8008,...,1113,2584,178,1096,179.0,1105.0,2.039358e-07,0.000001,0.000001,0.000003

In [9]:
cntr_val.columns

Index(['시도', '시군구', '행정구역코드', '법정구역코드', '년도', 'EQ5D', '학사_비율', '소득액',
       '실업급여지급자수(년)', '실업급여지급건수(년)', '실업급여지급액(년)', '인구수', '경제활동가능인구',
       '인구_실업급여자_비율', '경제활동가능인구_실업급여자_비율', '계_전체인구', '0-4세_전체인구', '5-9세_전체인구',
       '10-14세_전체인구', '15-19세_전체인구', '20-24세_전체인구', '25-29세_전체인구',
       '30-34세_전체인구', '35-39세_전체인구', '40-44세_전체인구', '45-49세_전체인구',
       '50-54세_전체인구', '55-59세_전체인구', '60-64세_전체인구', '65-69세_전체인구',
       '70-74세_전체인구', '75-79세_전체인구', '80-84세_전체인구', '85-89세_전체인구',
       '90-94세_전체인구', '95-99세_전체인구', '100세이상_전체인구', '계_여성인구', '0-4세_여성인구',
       '5-9세_여성인구', '10-14세_여성인구', '15-19세_여성인구', '20-24세_여성인구', '25-29세_여성인구',
       '30-34세_여성인구', '35-39세_여성인구', '40-44세_여성인구', '45-49세_여성인구',
       '50-54세_여성인구', '55-59세_여성인구', '60-64세_여성인구', '65-69세_여성인구',
       '70-74세_여성인구', '75-79세_여성인구', '80-84세_여성인구', '85-89세_여성인구',
       '90-94세_여성인구', '95-99세_여성인구', '100세이상_여성인구', '면적', '지하철_노선_개수',
       '지하철_역_개수', '도로_노드_개수', '도로_링크_개수', '버스_노선_개수', '버스_정류장_개수',
       '대중교통_노선_개수', '대중교통_정류장_역_개수', '대중교통_노선_면적', '대중교통_역_노선_면적', '도로_노드_면적',
       '도로_링크_면적'],
      dtype='object')

In [10]:
cntr_val = cntr_val[['시도', '시군구', '행정구역코드', '법정구역코드', '년도','학사_비율','소득액','EQ5D','인구수','0-4세_전체인구', '5-9세_전체인구',
       '10-14세_전체인구', '15-19세_전체인구', '20-24세_전체인구', '25-29세_전체인구',
       '30-34세_전체인구', '35-39세_전체인구', '40-44세_전체인구', '45-49세_전체인구',
       '50-54세_전체인구', '55-59세_전체인구', '60-64세_전체인구', '65-69세_전체인구',
       '70-74세_전체인구', '75-79세_전체인구', '80-84세_전체인구', '85-89세_전체인구',
       '90-94세_전체인구', '95-99세_전체인구', '100세이상_전체인구', '계_여성인구', '0-4세_여성인구',
       '5-9세_여성인구', '10-14세_여성인구', '15-19세_여성인구', '20-24세_여성인구', '25-29세_여성인구',
       '30-34세_여성인구', '35-39세_여성인구', '40-44세_여성인구', '45-49세_여성인구',
       '50-54세_여성인구', '55-59세_여성인구', '60-64세_여성인구', '65-69세_여성인구',
       '70-74세_여성인구', '75-79세_여성인구', '80-84세_여성인구', '85-89세_여성인구',
       '90-94세_여성인구', '95-99세_여성인구', '100세이상_여성인구', '면적','대중교통_노선_개수', '대중교통_정류장_역_개수', '대중교통_노선_면적', '대중교통_역_노선_면적', '도로_노드_면적',
       '도로_링크_면적']]

cntr_val = cntr_val.astype({'행정구역코드':str,'법정구역코드':str})
cntr_val['시도'] = cntr_val['시도'].apply(lambda x:city_sido_change(x))
cntr_val['행정구역코드'] = cntr_val['행정구역코드'].apply(lambda x:SGGcode_change(x))

cntr_val

,시도,시군구,행정구역코드,법정구역코드,년도,학사_비율,소득액,EQ5D,인구수,0-4세_전체인구,...,90-94세_여성인구,95-99세_여성인구,100세이상_여성인구,면적,대중교통_노선_개수,대중교통_정류장_역_개수,대중교통_노선_면적,대중교통_역_노선_면적,도로_노드_면적,도로_링크_면적
0,서울특별시,종로구,11010,11110,2015,0.388313,2755607,0.950,161521,4397.5,...,339.0,85.0,14.5,23912894,149.0,410.0,6.230948e-06,0.000017,0.000014,0.000041
1,서울특별시,종로구,11010,11110,2016,0.388313,2737610,0.968,154398,4302.0,...,340.5,93.5,16.0,23912883,149.0,410.0,6.230951e-06,0.000017,0.000014,0.000041
2,서울특별시,종로구,11010,11110,2017,0.388313,2870292,0.957,157277,4181.0,...,351.0,98.0,20.5,23912788,149.0,410.0,6.230976e-06,0.000017,0.000014,0.000041
3,서울특별시,종로구,11010,11110,2018,0.388313,3007628,0.952,157967,3989.0,...,383.5,104.0,21.0,23913318,149.0,410.0,6.230838e-06,0.000017,0.000014,0.000041
4,서울특별시,중구,11020,11140,2015,0.327387,2922120,0.952,128478,4437.5,...,256.0,52.0,6.5,9960549,176.0,264.0,1.766971e-05,0.000027,0.000027,0.000073
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
259,경기도,가평군,31370,41820,2018,0.185385,1893631,0.970,59957,1772.0,...,256.0,64.5,8.0,843271028,72.0,923.0,8.538180e-08,0.000001,0.000001,0.000003
260,경기도,양평군,31380,41830,2015,0.232083,1571897,0.952,101930,3721.5,...,346.0,90.5,11.0,877690918,179.0,1105.0,2.039442e-07,0.000001,0.000001,0.000003
261,경기도,양평군,31380,41830,2016,0.232083,1637534,0.950,105709,3723.5,...,362.5,102.5,10.0,877691672,179.0,1105.0,2.039441e-07,0.000001,0.000001,0.000003
262,경기도,양평군,31380,41830,2017,0.232083,1708265,0.953,109359,3684.0,...,387.0,111.0,11.5,877693097,179.0,1105.0,2.039437e-07,0.000001,0.000001,0.000003
263,경기도,양평군,31380,41830,2018,0.232083,1785488,0.947,111094,3532.0,...,436.0,111.5,13.5,877727400,179.0,1105.0,2.039358e-07,0.000001,0.000001,0.000003

In [12]:
# 도서관 통제변인(도서관장서수, 면적, 개관일, 도서관 연식...), 종속 변인(도서관 주제별 대출량, 대출량)

city_lib_info = pd.read_excel('../data/temporary_storage/3_city_lib_info.xlsx')
city_lib_info = city_lib_info.astype({'행정구역코드':str,'법정구역코드':str})
city_lib_info

,년도,시도,시군구,행정구역코드,법정구역코드,도서관 수,시설_연면적,개관일수,AGE,도서_국내_총류,...,대출권수_성인_종교,대출권수_성인_사회과학,대출권수_성인_순수과학,대출권수_성인_기술과학,대출권수_성인_예술,대출권수_성인_언어,대출권수_성인_문학,대출권수_성인_역사,총_국내도서권수,총_대출권수
0,2015,경기도,가평군,31370,41820,4,1569.057500,357.000000,13.000000,15638,...,3252.0,17801.0,11435.0,10045.0,6277.0,7663.0,77893.0,10509,322939,203411.0
1,2015,경기도,고양시,31100,41280,13,3465.230769,324.692308,9.538462,73154,...,37518.0,270033.0,130301.0,126870.0,72416.0,94979.0,794073.0,182132,1423094,2830810.0
2,2015,경기도,과천시,31110,41290,3,6050.326667,299.000000,16.666667,27516,...,7753.0,49906.0,9411.0,32767.0,28222.0,13387.0,119659.0,30063,603320,650898.0
3,2015,경기도,광명시,31060,41210,3,8834.543333,299.000000,12.666667,29454,...,14487.0,112808.0,46186.0,53784.0,24239.0,36095.0,283360.0,65821,661989,1113539.0
4,2015,경기도,광주시,31250,41610,5,2432.400000,298.800000,10.000000,28761,...,11217.0,72700.0,44266.0,37119.0,19664.0,22015.0,224527.0,46808,547796,815641.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
259,2018,인천광역시,부평구,23060,28237,6,2678.848333,292.333333,15.500000,30044,...,10346.0,86261.0,40047.0,45414.0,32327.0,22328.0,263801.0,48271,683315,826794.0
260,2018,인천광역시,서구,23080,28260,8,2364.548750,281.750000,10.000000,29571,...,11182.0,96265.0,59757.0,51336.0,23958.0,41979.0,320470.0,62893,660996,1028336.0
261,2018,인천광역시,연수구,23040,28185,5,2344.510000,252.200000,6.000000,22290,...,7306.0,69139.0,31956.0,33804.0,26280.0,18604.0,206637.0,42306,414927,651270.0
262,2018,인천광역시,옹진군,23320,28720,1,352.000000,256.000000,19.000000,1689,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,46635,0.0
263,2018,인천광역시,중구,23010,28110,4,1671.605000,292.500000,7.000000,9678,...,3831.0,32607.0,17493.0,16061.0,16631.0,13569.0,100233.0,19620,217990,325567.0

In [13]:
sgg_data = pd.merge(socio_index,cntr_val, on=['시도','시군구','년도','행정구역코드'], how='inner')
sgg_data = pd.merge(sgg_data,city_lib_info, on=['시도','시군구','년도','행정구역코드','법정구역코드'], how='inner')

sgg_data

,시도,시군구,년도,행정구역코드,사회적_불평등_지수,법정구역코드,학사_비율,소득액,EQ5D,인구수,...,대출권수_성인_종교,대출권수_성인_사회과학,대출권수_성인_순수과학,대출권수_성인_기술과학,대출권수_성인_예술,대출권수_성인_언어,대출권수_성인_문학,대출권수_성인_역사,총_국내도서권수,총_대출권수
0,서울특별시,종로구,2015,11010,1.602852,11110,0.388313,2755607,0.950,161521,...,17391.0,94729.0,20318.0,54756.0,45118.0,23072.0,203578.0,50629,740940,717640.0
1,서울특별시,종로구,2016,11010,1.630460,11110,0.388313,2737610,0.968,154398,...,13398.0,79143.0,25622.0,40677.0,50327.0,18838.0,203339.0,46400,748323,595733.0
2,서울특별시,종로구,2017,11010,1.706963,11110,0.388313,2870292,0.957,157277,...,10790.0,73312.0,23516.0,35504.0,30129.0,18736.0,180930.0,41023,747825,520196.0
3,서울특별시,종로구,2018,11010,1.322523,11110,0.388313,3007628,0.952,157967,...,11210.0,71374.0,22571.0,33391.0,26430.0,18174.0,176200.0,40029,744293,500248.0
4,서울특별시,중구,2015,11020,-0.162058,11140,0.327387,2922120,0.952,128478,...,8382.0,57919.0,12051.0,28969.0,45438.0,17865.0,141274.0,36818,367606,500023.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
259,경기도,가평군,2018,31370,-1.314690,41820,0.185385,1893631,0.970,59957,...,3241.0,19757.0,12052.0,9468.0,5554.0,5665.0,67646.0,11288,377584,187671.0
260,경기도,양평군,2015,31380,-2.159563,41830,0.232083,1571897,0.952,101930,...,4194.0,22572.0,8951.0,17692.0,8472.0,5970.0,88602.0,16110,275568,232211.0
261,경기도,양평군,2016,31380,-1.164249,41830,0.232083,1637534,0.950,105709,...,3453.0,23270.0,8439.0,16123.0,7502.0,4877.0,77497.0,14712,419207,207718.0
262,경기도,양평군,2017,31380,-0.595251,41830,0.232083,1708265,0.953,109359,...,2953.0,19914.0,7556.0,16891.0,6317.0,4728.0,64265.0,12584,438235,181383.0
263,경기도,양평군,2018,31380,-1.799638,41830,0.232083,1785488,0.947,111094,...,3575.0,21500.0,8290.0,18092.0,6876.0,4483.0,68551.0,12951,430077,190913.0

In [14]:
sgg_data.corr()

,년도,사회적_불평등_지수,학사_비율,소득액,EQ5D,인구수,0-4세_전체인구,5-9세_전체인구,10-14세_전체인구,15-19세_전체인구,...,대출권수_성인_종교,대출권수_성인_사회과학,대출권수_성인_순수과학,대출권수_성인_기술과학,대출권수_성인_예술,대출권수_성인_언어,대출권수_성인_문학,대출권수_성인_역사,총_국내도서권수,총_대출권수
년도,1.000000e+00,-0.013967,1.428591e-15,0.228525,0.317747,0.009931,-0.062559,0.002002,-0.040523,-0.064854,...,-0.046074,0.031770,0.046563,0.021708,-0.021825,0.000134,0.031696,-0.029895,0.084021,-0.001151
사회적_불평등_지수,-1.396677e-02,1.000000,-6.859134e-02,-0.007353,0.125428,0.017530,0.019364,0.026828,0.028681,0.029902,...,0.092287,0.107688,0.119377,0.088769,0.055434,0.101408,0.102809,0.077743,0.050963,0.090591
학사_비율,1.428591e-15,-0.068591,1.000000e+00,0.441345,0.292968,0.315739,0.272563,0.271744,0.298965,0.297403,...,0.296810,0.355187,0.292343,0.345520,0.378276,0.312057,0.344241,0.317211,0.190732,0.355372
소득액,2.285251e-01,-0.007353,4.413449e-01,1.000000,0.247931,0.132622,0.157435,0.155616,0.128354,0.097010,...,0.212272,0.214398,0.188299,0.227348,0.348644,0.192092,0.199255,0.195217,0.261427,0.200224
EQ5D,3.177471e-01,0.125428,2.929676e-01,0.247931,1.000000,0.078050,0.082108,0.090643,0.081904,0.054285,...,0.100332,0.147437,0.107962,0.149827,0.104701,0.128053,0.131058,0.094171,0.117520,0.145031
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
대출권수_성인_언어,1.337857e-04,0.101408,3.120566e-01,0.192092,0.128053,0.793925,0.819098,0.832165,0.832593,0.801668,...,0.953347,0.958264,0.949299,0.952354,0.837885,1.000000,0.948517,0.951030,0.831466,0.958800
대출권수_성인_문학,3.169604e-02,0.102809,3.442409e-01,0.199255,0.131058,0.831649,0.849036,0.872785,0.870413,0.836672,...,0.915369,0.986413,0.973961,0.971631,0.876322,0.948517,1.000000,0.908139,0.848848,0.979390
대출권수_성인_역사,-2.989462e-02,0.077743,3.172110e-01,0.195217,0.094171,0.777198,0.800703,0.808081,0.815521,0.794161,...,0.951103,0.920730,0.912446,0.919317,0.817114,0.951030,0.908139,1.000000,0.819374,0.928241
총_국내도서권수,8.402141e-02,0.050963,1.907321e-01,0.261427,0.117520,0.785799,0.793873,0.799028,0.799543,0.794450,...,0.885078,0.881152,0.824987,0.908122,0.838016,0.831466,0.848848,0.819374,1.000000,0.882470
총_대출권수,-1.151085e-03,0.090591,3.553721e-01,0.200224,0.145031,0.854727,0.872515,0.887341,0.891121,0.865373,...,0.938897,0.986596,0.947012,0.987994,0.889576,0.958800,0.979390,0.928241,0.882470,1.000000

In [15]:
for i in sgg_data.corr()['총_대출권수'].index:
    print(i," : ",sgg_data.corr()['총_대출권수'][i])

년도  :  -0.0011510849893273435
사회적_불평등_지수  :  0.09059133313573645
학사_비율  :  0.3553720806549589
소득액  :  0.2002236162940897
EQ5D  :  0.14503061286352947
인구수  :  0.8547269146233242
0-4세_전체인구  :  0.8725154217857711
5-9세_전체인구  :  0.8873412087225063
10-14세_전체인구  :  0.8911205152129682
15-19세_전체인구  :  0.8653730688753755
20-24세_전체인구  :  0.8229763430648164
25-29세_전체인구  :  0.7732668084839717
30-34세_전체인구  :  0.8066759923131003
35-39세_전체인구  :  0.864474359152141
40-44세_전체인구  :  0.8793443181459792
45-49세_전체인구  :  0.8677788296388077
50-54세_전체인구  :  0.8323523042264678
55-59세_전체인구  :  0.7987081907169644
60-64세_전체인구  :  0.7734069346015982
65-69세_전체인구  :  0.7715616186495724
70-74세_전체인구  :  0.7803890668800587
75-79세_전체인구  :  0.7797367960822346
80-84세_전체인구  :  0.7996982827677095
85-89세_전체인구  :  0.82503059102816
90-94세_전체인구  :  0.8335107320298527
95-99세_전체인구  :  0.8155806767129741
100세이상_전체인구  :  0.7765063418455709
계_여성인구  :  0.8570062983049169
0-4세_여성인구  :  0.871910100419922
5-9세_여성인구  :  0.8864361334475752
10-14세_여성인구  :  0.8901239709954301
15-19세_여성인구  :  0.8660133073173403
20-24세_여성인구  :  0.8168868802336127
25-29세_여성인구  :  0.7647426187027901
30-34세_여성인구  :  0.8133533716808103
35-39세_여성인구  :  0.8739058936975044
40-44세_여성인구  :  0.883258898733912
45-49세_여성인구  :  0.8615853086192793
50-54세_여성인구  :  0.8222680435995617
55-59세_여성인구  :  0.7871179823127146
60-64세_여성인구  :  0.766033905459917
65-69세_여성인구  :  0.7714821793396693
70-74세_여성인구  :  0.7827271002171542
75-79세_여성인구  :  0.778936444836823
80-84세_여성인구  :  0.8026082987657881
85-89세_여성인구  :  0.8266037255937866
90-94세_여성인구  :  0.8308977822837278
95-99세_여성인구  :  0.8224222698994409
100세이상_여성인구  :  0.7871481004482482
면적  :  0.04251045281797072
대중교통_노선_개수  :  0.4499812638860016
대중교통_정류장_역_개수  :  0.5470967478096296
대중교통_노선_면적  :  -0.13416942110537308
대중교통_역_노선_면적  :  -0.05824026828531272
도로_노드_면적  :  0.0671809569838795
도로_링크_면적  :  0.0693328934617334
도서관 수  :  0.8132634663193024
시설_연면적  :  0.3096792927731391
개관일수  :  0.05442456017267132
AGE  :  -0.13272558315806118
도서_국내_총류  :  0.87043326491652
도서_국내_철학  :  0.8778913915842099
도서_국내_종교  :  0.8323882627160981
도서_국내_사회과학  :  0.8499278051048614
도서_국내_순수과학  :  0.8959706765855683
도서_국내_기술과학  :  0.8260242503815918
도서_국내_예술  :  0.852570353298156
도서_국내_언어  :  0.8472322743060455
도서_국내_문학  :  0.8980057254299212
도서_국내_역사  :  0.8761665371705869
대출권수_어린이_총류  :  0.9308161032144942
대출권수_어린이_철학  :  0.9051993605388989
대출권수_어린이_종교  :  0.9025456808588648
대출권수_어린이_사회과학  :  0.9235741362657718
대출권수_어린이_순수과학  :  0.9080478948814014
대출권수_어린이_기술과학  :  0.8962946729678138
대출권수_어린이_예술  :  0.7717960313438501
대출권수_어린이_언어  :  0.7442539834769256
대출권수_어린이_문학  :  0.9035855109937301
대출권수_어린이_역사  :  0.8954436989001784
대출권수_청소년_총류  :  0.9187212550108261
대출권수_청소년_철학  :  0.8833105469040895
대출권수_청소년_종교  :  0.7504824026652738
대출권수_청소년_사회과학  :  0.9043204303643266
대출권수_청소년_순수과학  :  0.9202487758590084
대출권수_청소년_기술과학  :  0.8854057445773192
대출권수_청소년_예술  :  0.6529262703729727
대출권수_청소년_언어  :  0.8761143109879596
대출권수_청소년_문학  :  0.9422162092975974
대출권수_청소년_역사  :  0.9157665682789753
대출권수_성인_총류  :  0.9639818554420071
대출권수_성인_철학  :  0.9762601463110582
대출권수_성인_종교  :  0.9388965397688319
대출권수_성인_사회과학  :  0.9865962466705058
대출권수_성인_순수과학  :  0.9470118054517328
대출권수_성인_기술과학  :  0.9879936344622566
대출권수_성인_예술  :  0.889575698309345
대출권수_성인_언어  :  0.9587999013852133
대출권수_성인_문학  :  0.9793901083495125
대출권수_성인_역사  :  0.9282406671396707
총_국내도서권수  :  0.882470482306483
총_대출권수  :  1.0

In [16]:
print(sgg_data.columns)

Index(['시도', '시군구', '년도', '행정구역코드', '사회적_불평등_지수', '법정구역코드', '학사_비율', '소득액',
       'EQ5D', '인구수',
       ...
       '대출권수_성인_종교', '대출권수_성인_사회과학', '대출권수_성인_순수과학', '대출권수_성인_기술과학',
       '대출권수_성인_예술', '대출권수_성인_언어', '대출권수_성인_문학', '대출권수_성인_역사', '총_국내도서권수',
       '총_대출권수'],
      dtype='object', length=106)

In [17]:
sgg_data[sgg_data['법정구역코드'].isna()]

Empty DataFrame
Columns: [시도, 시군구, 년도, 행정구역코드, 사회적_불평등_지수, 법정구역코드, 학사_비율, 소득액, EQ5D, 인구수, 0-4세_전체인구, 5-9세_전체인구, 10-14세_전체인구, 15-19세_전체인구, 20-24세_전체인구, 25-29세_전체인구, 30-34세_전체인구, 35-39세_전체인구, 40-44세_전체인구, 45-49세_전체인구, 50-54세_전체인구, 55-59세_전체인구, 60-64세_전체인구, 65-69세_전체인구, 70-74세_전체인구, 75-79세_전체인구, 80-84세_전체인구, 85-89세_전체인구, 90-94세_전체인구, 95-99세_전체인구, 100세이상_전체인구, 계_여성인구, 0-4세_여성인구, 5-9세_여성인구, 10-14세_여성인구, 15-19세_여성인구, 20-24세_여성인구, 25-29세_여성인구, 30-34세_여성인구, 35-39세_여성인구, 40-44세_여성인구, 45-49세_여성인구, 50-54세_여성인구, 55-59세_여성인구, 60-64세_여성인구, 65-69세_여성인구, 70-74세_여성인구, 75-79세_여성인구, 80-84세_여성인구, 85-89세_여성인구, 90-94세_여성인구, 95-99세_여성인구, 100세이상_여성인구, 면적, 대중교통_노선_개수, 대중교통_정류장_역_개수, 대중교통_노선_면적, 대중교통_역_노선_면적, 도로_노드_면적, 도로_링크_면적, 도서관 수, 시설_연면적, 개관일수, AGE, 도서_국내_총류, 도서_국내_철학, 도서_국내_종교, 도서_국내_사회과학, 도서_국내_순수과학, 도서_국내_기술과학, 도서_국내_예술, 도서_국내_언어, 도서_국내_문학, 도서_국내_역사, 대출권수_어린이_총류, 대출권수_어린이_철학, 대출권수_어린이_종교, 대출권수_어린이_사회과학, 대출권수_어린이_순수과학, 대출권수_어린이_기술과학, 대출권수_어린이_예술, 대출권수_어린이_언어, 대출권수_어린이_문학, 대출권수_어린이_역사, 대출권수_청소년_총류, 대출권수_청소년_철학, 대출권수_청소년_종교, 대출권수_청소년_사회과학, 대출권수_청소년_순수과학, 대출권수_청소년_기술과학, 대출권수_청소년_예술, 대출권수_청소년_언어, 대출권수_청소년_문학, 대출권수_청소년_역사, 대출권수_성인_총류, 대출권수_성인_철학, 대출권수_성인_종교, 대출권수_성인_사회과학, 대출권수_성인_순수과학, 대출권수_성인_기술과학, ...]
Index: []

[0 rows x 106 columns]

In [18]:
sgg_data.to_csv('../data/result/result.csv',index=False)